### ISSUE TITLE
Javascript error on cancel of the block user modal.

### ISSUE THREAD

**Issue by awhileback** [Radi85/Comment#230] opened 2021-09-03 20:13 UTC
### Environment
* python version 3.6
* django Version 3.2
* django-comments-dab 2.7.0

### Describe the bug
Closing the "block user" modal raises a javascript error and the modal fails to close.

```
15:05:52.214 comment.js:41 Uncaught TypeError: Cannot read property 'classList' of null
    at hideModal (comment.js:41)
    at HTMLDocument.<anonymous> (comment.js:790)
```

### Steps To Reproduce
1. post a comment
2. login as admin
3. click the lock icon to block a user, and cancel the block modal

### Expected behavior
Cancel the action and close the modal.

**Comment by awhileback** [comment] 2021-09-03 22:29
At a guess after glancing around the js file, it seems this might be related to selection of disabled functions.  It seems to find "nearest" as followModal or CreateAnonymousCommentModal, both of which I disabled in settings.

If I remove the hide functions for those (follow and CreateAnonymous) modals (around lines 40-50), as well as the references to those functions in the click listener (around lines 790-800) the problems go away.

**Comment by abhiabhi94** [comment] 2021-09-04 11:49
Thanks for taking the time to report the issue, and on its initial investigation, i also get an error after closing the modal for blocking the user. although the modal closes successfully for me, i get an error:
```js
Uncaught TypeError: createAnonymousCommentModal is null
    hideCreateAnonymousCommentModal http://localhost:8000/static/js/comment.js:46
    <anonymous> http://localhost:8000/static/js/comment.js:792
```
i will try to investigate more on this. if you could give me an additional information about the custom settings that you're using for `django-comments-dab`, it would be great.

**Comment by abhiabhi94** [comment] 2021-09-04 12:43
@awhileback  can you verify whether the linked pull request fixes your issue?

**Comment by awhileback** [comment] 2021-09-05 01:18
```
PROFILE_APP_NAME = 'users'
PROFILE_MODEL_NAME = 'CustomUser'
COMMENT_PROFILE_API_FIELDS = ('user_name')
COMMENT_USER_API_FIELDS = ['id', 'user_name']
COMMENT_PER_PAGE = 50
COMMENT_FLAGS_ALLOWED = 10
COMMENT_FROM_EMAIL = os.environ.get('DO_EMAIL_ADDR')
COMMENT_ALLOW_BLOCKING_USERS = True
COMMENT_ALLOW_MODERATOR_TO_BLOCK = True
COMMENT_FLAG_REASONS = [
    (1, ('Spam')),
    (2, ('Abusive')),
]
```

The linked PR still fails in a similar manner, it mentions the followModal on line 792...

```
Uncaught TypeError: Cannot read property 'classList' of null
    at hideModal (comment.js:41)
    at HTMLDocument.<anonymous> (comment.js:792)
```

**Comment by abhiabhi94** [comment] 2021-09-05 11:48
@awhileback Thank you so much for the information. I think the main cause of the issue is that there is being an attempt to close/hide a modal element that doesn't exist inside the DOM(document object model)

i have added the checks inside the `hideModal` and `showModal` functions to verify and process only if the element exists in the linked pull request. Would it be possible for you to verify this and confirm if this works on your end now.

**Closed** 2021-09-05 16:08 UTC
Labels: bug, work in progress

**Comment by awhileback** [comment] 2021-09-06 02:13
Thanks, all working fine!

**Comment by abhiabhi94** [comment] 2021-09-06 13:20
thanks, for checking and the relay of information back and forth.
