### ISSUE TITLE
Dynamic pagination update

### ISSUE THREAD

**Issue by boryskuczkowski** [Radi85/Comment#2] opened 2018-10-14 17:56 UTC
Hello there ;)

So, there is one small thing that probably involves ajax call in comments.js and the thing is the pagination update. What I mean by that is if user selects option to have paginated comments and comments are added the pagination won't show up (update) until the page holding the code is rendered again (refreshed).
The same goes for deleting comments, so perhaps you have couple of pages of comments, you delete all the comments from the particular page of pagination, the comments will get deleted but no comments from previous pages get shown, they won't update until the page is re-fetched.
It would be nice to have that feature of dynamic update set.

**Comment by boryskuczkowski** [comment] 2018-10-22 22:28
Alright, this is an ugly hack, please tell me what do you think about this approach?

in comment/templates/base.html
```
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/comment.css' %}">
<div id="allcomments">  // new wrapping div here
<section id="comments" class="{% block btn_name %}my-5 mx-3{% endblock btn_name %}">
    <strong class="border-bottom bb"><span class="js-comment-number">{{model_object.comments.all.count}}</span> Comments</strong>
    <hr class="hr"/>
    <div class="js-comment comment mb-5">
        {% include 'comment/create_comment.html' with button_name='comment' is_child=False placeholder="comment on this post..." %}
    </div>
    <div class="js-main-comment mt-5">
      {% for comment in comments %}
          {% include 'comment/parent_comment.html' %}
      {% endfor %}
    </div>
    <div class="modal fade" id="Modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
  </div>
</section>
{% if paginate and comments.paginator.num_pages > 1 %}
{% block pagination %}
{% include 'comment/pagination.html' with active_btn='bg-info' text_style='text-info' li_cls='page-item rounded mx-1' %}
{% endblock pagination %}
{% endif %}
</div> // end of wrapping div here
```



in comments.js:

```
    function commentCount(num){
        var $commentNumber = $(".js-comment-number");
        var result = Number($commentNumber.text())+num;
        $commentNumber.replaceWith("<span class='js-comment-number'>"+result+"</span>");
        // console.log(result);
  ->     if (result > 0 ){
  ->        $("#allcomments").load(" #allcomments");  // mind the space in second #allcomments
  ->         // console.log("updated allcomments");
  ->      }
  ->     else{}
    }
```

This is the easiest, laziest thing ever, however it addresses all of the issues. The only drawback is of course re-fetching substantial part of the site each time there is any movement in comments.

**Comment by Radi85** [comment] 2018-10-26 18:00
Hi broys, 
I have updated the app to cover pagination update issue, the pagination now is updated when posting or deleting a comment. Thanks for your idea which I started from and finally landed up with a satisfaction result. please clone the branch [Fix-pagination-update](https://github.com/Radi85/Comment/tree/Fix-pagination-update) and check it out in your project, I will update the master branch and app version after confirming that the issue is fixed.

**Comment by boryskuczkowski** [comment] 2018-10-26 21:30
Well, that is working great. Good job Radi :)

**Closed** 2018-10-27 13:37 UTC
